
LDLIBS= -lCoreFoundation -lFoundation

OBJECTS = \
	GSCache.o \
	GSFIFO.o \
	GSIOThreadPool.o \
	GSLinkedList.o \
	GSThreadPool.o \
	GSThroughput.o \
	GSTicker.o \
	GSIndexedSkipList.o \
	GSSkipMutableArray.o \
	GSUniqued.o \

include ${MYOS_PATH}/sdk/$(BASE_OS)/makefile-static
